# Generated by Django 4.1 on 2022-09-07 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
                ('prix', models.IntegerField()),
                ('vendu', models.BooleanField()),
                ('photo', models.FileField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArticle', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('dateLivraison', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ieme_mesure', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productivite', models.CharField(choices=[('Mauvais', 'Mauvais'), ('Moyen', 'Moyen'), ('Bon', 'Bon'), ('TresBon', 'Tresbon'), ('Excellent', 'Excellent')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeMesure', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('Femelle', 'Femelle'), ('Masculin', 'Masculin')], max_length=100)),
                ('telephone', models.IntegerField()),
                ('adresse', models.CharField(max_length=255)),
                ('motDePasse', models.CharField(max_length=100)),
                ('idMesure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.mesure')),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dream_back.utilisateur')),
                ('administrateurs', models.IntegerField(null=True)),
            ],
            bases=('dream_back.utilisateur',),
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=3)),
                ('idMesure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.mesure')),
                ('idUtilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.typemesure')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('idArticle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.article')),
                ('idProfessionnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.professionnel')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('idCommande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.commande')),
                ('idUtilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArticle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.article')),
                ('idCommande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.commande')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='idUtilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.utilisateur'),
        ),
        migrations.AddField(
            model_name='article',
            name='idCategorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.categorie'),
        ),
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('idPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.post')),
                ('idProfessionnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.professionnel')),
            ],
        ),
    ]
