# Generated by Django 4.1 on 2022-10-01 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dream_back', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesure',
            name='n_ieme_mesure',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='idMesure',
        ),
        migrations.AddField(
            model_name='mesure',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.utilisateur'),
        ),
    ]
