# Generated by Django 4.1 on 2022-09-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_back', '0003_utilisateur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.FileField(null=True, upload_to='photos'),
        ),
    ]
