# Generated by Django 4.1 on 2022-09-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_back', '0004_alter_utilisateur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(choices=[('Féminin', 'Femelle'), ('Masculin', 'Masculin')], max_length=100),
        ),
    ]
