# Generated by Django 4.1 on 2022-09-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_back', '0005_alter_utilisateur_sexe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='vendu',
            new_name='disponible',
        ),
    ]
