# Generated by Django 4.1 on 2022-09-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dream_back', '0006_rename_vendu_article_disponible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valeur',
            old_name='idUtilisateur',
            new_name='idTypeMesure',
        ),
        migrations.AddField(
            model_name='professionnel',
            name='idUtilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.utilisateur'),
        ),
    ]
