# Generated by Django 4.1 on 2022-09-25 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dream_back', '0007_rename_idutilisateur_valeur_idtypemesure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='idUtilisateurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dream_back.typemesure'),
        ),
    ]
