# Generated by Django 4.1 on 2022-09-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_back', '0008_administrateur_idutilisateurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateur',
            name='administrateurs',
        ),
        migrations.AlterField(
            model_name='appreciation',
            name='commentaire',
            field=models.TextField(null=True),
        ),
    ]
