# Generated by Django 4.1 on 2022-09-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_back', '0009_remove_administrateur_administrateurs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(choices=[('Féminin', 'Feminin'), ('Masculin', 'Masculin')], max_length=100),
        ),
    ]
