# Generated by Django 4.1 on 2022-09-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_back', '0011_alter_valeur_valeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valeur',
            name='idTypeMesure',
        ),
    ]
