# Generated by Django 4.1 on 2022-09-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_back', '0013_valeur_idtypemesure'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='img',
            field=models.FileField(default='', upload_to='photos'),
            preserve_default=False,
        ),
    ]
