# Generated by Django 4.1 on 2022-09-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_back', '0014_categorie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
    ]
