# Generated by Django 4.1 on 2022-09-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_back', '0015_alter_utilisateur_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciation',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
